apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  containers:
    - name: myapp
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mystorage
  volumes:
    - name: mystorage
      persistentVolumeClaim:
        claimName: my-pvc
