apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi              # Size of the storage
  accessModes:
    - ReadWriteOnce           # Only one pod can write at a time
  hostPath:
    path: "/mnt/data"         # Folder on your local system (works in Minikube)
